// Generated by inject-api-base.mjs — do not edit by hand.
// Netlify rewrites this file from STW_API_BASE on each build.
// The committed copy is the production default so a publish without that build still works.
window.STW_API_BASE = "https://api.splitthewine.app";
